services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jenkins-web-container
    ports:
      - "9000:8000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017
    volumes:
      - ./static:/app/static
      - ./templates:/app/templates
      - ./static/uploads:/app/static/uploads
      - .:/app  # attach volume for code
    restart: unless-stopped
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: jenkins-mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
